#ifndef YARP_WEIGHT_RETARGETING_COMPONENT_H
#define YARP_WEIGHT_RETARGETING_COMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(WEIGHT_RETARGETING_LOG_COMPONENT)

YARP_LOG_COMPONENT(WEIGHT_RETARGETING_LOG_COMPONENT, "WeightRetargetingModule")

#endif // YARP_WEIGHT_RETARGETING_COMPONENT_H
