#ifndef YARP_WEIGHT_RETARGETING_COMPONENT_H
#define YARP_WEIGHT_RETARGETING_COMPONENT_H

#include <yarp/os/LogComponent.h>

YARP_LOG_COMPONENT(WEIGHT_RETARGETING_LOG_COMPONENT, "WeightRetargeting")

#endif // YARP_WEIGHT_RETARGETING_COMPONENT_H
